exam/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("quiz.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.urls import path
from .views import ajaxQuestionsView,ModeView,ajaxAnswer,QuestionTemplate,CreateUser,QuestionTemplate
from django.contrib.auth.views import LoginView

app_name = "quiz"
urlpatterns = [
    path("",ModeView,name="mode"),
    path("create-account",CreateUser,name="register"),
   	path("login/", LoginView.as_view(),name="login"),
    path("mode/<mode>/",QuestionTemplate,name="question"),
    path("ajax-question/<mode>/",ajaxQuestionsView,name="questions"),
    path("ajax-answer/",ajaxAnswer,name="ajax"),
    path("q1/<mode>/",QuestionTemplate),
]

quiz/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    pass

quiz/views.py
from django.shortcuts import render,redirect
from django import forms
from django.contrib.auth.decorators import login_required
import random
from users.models import User
from django.contrib.auth.forms import UserCreationForm 

class AnswerKey:
    """ Container for questions and their respective answers 
    """

    def __init__(self, num, answers):
        self.id = int(num)
        self.answers = []
        for i in range(0, 8):
            assert answers[i] == "S" or answers[i] == "N"
            answer_head = "abcdefgh"
            self.answers.append((answer_head[i], answers[i]))

    def __repr__(self):
        return "AnswerKey{{id={}, answers={}}}".format(self.id, self.answers)



def answer_keys_from_file(filename):
    """ Reads the answer keys file from filename
        :parameter filename path string to answerkeys file
    """
    qa = []
    with open(filename, 'r') as aks:
        line = 1
        for ak in aks:
            ak_split = ak.strip().split()
            try:
                qa.append(AnswerKey(ak_split[0], ak_split[1]))
            except (IndexError, AssertionError):
                print("Couldn't read file. Input is malformed.")
                print("Line {}: {}".format(line, ak.strip()))
            line += 1
    
    return qa


def check_answers(ak, option, given_answer):
  """ Queries for answers and checks them
    :parameter ak An AnswerKey object
    :parameter num The number of answers to ask. Must be in (0,8]
    :parameter rand Whether the answers should be asked in random order """
  
  # legacy support (answer format changed)
  if given_answer.upper() == "A":
    given_answer = "S"
  elif given_answer.upper() == "D":
    given_answer = "N"

  for i in ak.answers:
    if i[0] == option and i[1] == given_answer:
      return True
  return False


class MyUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','password1','password2']
		fields = UserCreationForm.Meta.fields
    


def CreateUser(request):
  if request.user.is_superuser:
  # Checks if user is Superuser
    if request.method == "GET":
      form = MyUserCreationForm()
    elif request.method == "POST":
      form = MyUserCreationForm(request.POST)
      if form.is_valid():
        form.save()
        return redirect("/admin/")
    return render(request,"registration/register.html",{"form":form})
  return render(request,"registration/register.html",{"error":"You don't have access to this page"})



class ModeForm(forms.Form):
  """ModeForm definition."""
  mode = forms.IntegerField(min_value=1,max_value=3)
  start = forms.IntegerField(min_value=1,max_value=len(answer_keys_from_file("quiz/answerkeys.txt")),required=False)


@login_required
def ModeView(request):
  if request.method == "POST":
    form = ModeForm(request.POST)
    return render(request,"templates/questions.html",{"form":form})
  else:
    form = ModeForm()
    return render(request,"mode.html",{"form":form})





from django.http import JsonResponse 


@login_required
def ajaxQuestionsView(request,mode):
    aks = answer_keys_from_file("quiz/answerkeys.txt")
    mode = int(mode)
    if mode == 1:
      ak = random.sample(aks,k=4)
      questions = {}
      for a in ak:
        ak_seq = random.sample(range(0,8),k=4)
        questions[a.id] = []
        for i in ak_seq:
          questions[a.id].append(a.answers[i][0])
    
    elif mode == 2 or mode == 3:
      start = int(request.POST['start'])
      end = start + 8 if start + 8 < len(aks) else len(aks)
      ak = []
      for i in range(start,end):
        ak.append(aks[i-1])
      questions = {}
      for a in ak:
        if mode == 2:
          ak_seq = random.sample(range(0,8),k=8)
        elif mode == 3:
          ak_seq = range(0,8)
        questions[a.id] = []
        for i in ak_seq:
          questions[a.id].append(a.answers[i][0])     

    else:
        questions["error"] = "Wrong Mode"
    return JsonResponse({"questions":questions,"question_keys":list(questions)})



@login_required
def ajaxAnswer(request):
  aks = answer_keys_from_file("quiz/answerkeys.txt")
  answer = None
  for key,item in request.POST.items():
    try:
      number,option = key.split("-")
      number = int(number)
      answer = check_answers(aks[number], option, item)
    except:
      continue
  return JsonResponse({"answer":answer})

# @login_required
def QuestionTemplate(request,mode):
  return render(request, "question-1.html",{"mode":mode})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login
from user.models import HandyUser as User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import DetailView,ListView
from workers.models import Worker
from clients.models import Client
from contract.models import Contract


# Create your views here.

class HandyUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = UserCreationForm.Meta.fields + ('is_client','email')
    
def assignStatus(user,is_client):
	if is_client == 'on':
		return Client(user=user)
	else:
		return Worker(user=user)

def RegisterView(request):
	if request.method == "GET":
		form = HandyUserCreationForm()
	elif request.method == "POST":
		form = HandyUserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			'''Obtain proper user from db and create either Client or Worker model for it
				depending on the 'is_client' value
			'''
			user = User.objects.get(username=request.POST['username'])
			is_client = request.POST['is_client']
			person = assignStatus(user,is_client)
			person.save()

			username = request.POST['username']
			password = request.POST['password1']
			auth_user = authenticate(request,username=username,password=password)
			if auth_user is not None:
				login(request,auth_user)
			return redirect("/user/")
	return render(request,"registration/register.html",{"form":form})


@method_decorator(login_required(),name="dispatch")
class ProfileView(DetailView):
	template_name = "user/index.html"
	context_object_name = "person"

	def get_object(self):
		user = self.request.user
		if user.is_client:
			return Client.objects.get(user=user)
		else:
			return Worker.objects.get(user=user)
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		user = self.request.user
		if user.is_client:
			all_contracts = Contract.objects.filter(client__user=user).order_by("created_on")
			active_contracts = all_contracts.filter(work_status="AC")
			inactive_contracts = all_contracts.filter(work_status="NB")
			context['contracts'] = all_contracts
			context['active_contracts'] = active_contracts
			context['inactive_contracts'] = inactive_contracts
		return context

quiz/templates/answers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Answers</title>
</head>
<body>
    {% for answer,options in answers.items %}
    <div>
        <h4>{{answer}}</h4>
        
        {% for option,value in options.items %}
            
            {% if value %}
                <p>{{option}}:Correct!</p>
            {% else %}
                <p>{{option}}:Wrong!</p>
            {% endif %}
                
        {% endfor %}
            
    </div>
    {% endfor %}
</body>
</html>

quiz/templates/base.html
{% load static %}
<html>
  <head>
      <title>{% block title %}MCQ Quiz{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="{% static 'jquery-3.4.1.min.js' %}" ></script>
    <script src="{% static 'popper.min.js' %}" ></script>
    <script src="{% static 'bootstrap.min.js' %}" ></script>
    </head>

    <body class="container">
    {% block content %}
    {% endblock content %}

    </body>
    <html>

quiz/templates/mode.html
{% extends 'base.html' %}
{% load static %}
        {% block title %}Select a Mode{% endblock %}
    {% block content %}

    <h2>Press 1, 2, or 3 to continue</h2>
    <section>
        <h4>
            Which mode of operation do you want?
        </h4>
        <ol>
            <li>
                Random question, 4 out of 8 answers in random order
            </li>
            <li>
                Selectable question start, 8 out of 8 answers in random order
            </li>
            <li>
                Selectable question start, 8 out of 8 answers in sequential order
            </li>
        </ol>
    </section>
    <section class="row mode-buttons">
        <div class="col-md-3">
            <a href="{% url 'quiz:question' 1 %}" class="btn btn-default btn-primary">1</a>
        </div>
        <div class="col-md-3">
            <a href="{% url 'quiz:question' 2 %}" class="btn btn-default btn-primary">2</a>
        </div>
        <div class="col-md-3">
            <a href="{% url 'quiz:question' 3 %}" class="btn btn-default btn-primary">3</a>
        </div>
    </section>
        <script>
        $("div.start-container").hide()
        $("input[name='mode']").change(function(event){
            if ($(this).val() == 2 || $(this).val() == 3) {
                $("div.start-container").show()
            }
            else{
                $("div.start-container").hide()

            }
        })
      </script>
    {% endblock %}

quiz/templates/question-1.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
                    <!-- <span class="fa fa-check-circle fa-2x text-success"></span> -->
                    <!-- <span class="fa fa-times-circle fa-2x text-danger"></span> -->
<form action="" method="POST">
    {% csrf_token %}
</form>
<script>
    var csrf_token = '{{csrf_token}}';
    var mode = '{{mode}}';
    var json_data;
    var unanswered = []
    var unansweredOptions = {}

     function newQuestion(number,option){
        //Generates HTML for a new question
        var template = $("<div class='question-container' id='"+number+"'>")
        var heading = $("<div class='question'>").append($("<h5>").text("Question "+number))
        heading.append($("<img class='img-fluid' src='/media/"+number+".jpg' alt='"+number+"'>"))
        template.append(heading)
        template.append(newOption(number,option))
        return template
    }
    function newOption(number,option){
        //Generates HTML for new option in a question
        var container = $("<div class='options' id='"+number+"-"+option+"'>")
        var row1 = $("<div class='row'>") 
        var row2 = $("<div class='row option'>") 
        row1.append($("<label class='col-md-2'>").text("Option "+option.toUpperCase()))
        row1.append($("<div class='col-md-10'>").append($("<img class='img-fluid' src='/media/"+number+option+".jpg' alt='"+number+option+"'>")))
        container.append(row1)
        var content = $("<div class='col-md-11 input-group'>")
        content.append($("<div class='input-group-prepend'>").append($("<span class='input-group-text'>").text("Enter A or D")))
        content.append($("<input type='text' class='form-control answer' name='"+number+"-"+option+"' required>"))
        row2.append(content)
        row2.append($("<div class='col-md-1'>").append($("<span class='fa fa-2x a-status'>")))
        container.append(row2)
        return container
    }

    function changeOption(number,option) {
       // newOption(number,option).insertAfter($("input.answer").last())
        newOption(number,option).insertAfter($("div.options").last())

    }

    var checkInputAnswer = function(event){
        //Queries backend for answer of an input
        input = $(this);
        val = input.val().toUpperCase()
        if (val != "A" && val != "D" ){
            input.val("")
        } else {
            input.val(val)
            $.ajax({
                headers: { "X-CSRFToken": csrf_token },
                url:"{% url 'quiz:ajax' %}",
                type:"POST",
                data:input.serialize(),
                success:function(data){
                    params = input.serializeArray()[0]
                    num_option = params.name.split("-")
                    num = num_option[0]
                    option = num_option[1]
                    let status_span = $("#"+params.name+" .col-md-1 span.a-status")
                    input.attr({"disabled":""})
                    if(data.answer == true){
                        status_span.removeClass("text-danger fa-times-circle")
                       status_span.addClass("text-success fa-check-circle")
                    } else{
                       status_span.removeClass("text-success fa-times-circle")
                       status_span.addClass("text-danger fa-times-circle")
                    }
                    if (askQ(num,option) == false) askQ()
                }
            })
        }
    }

    $.ajax({
        //Runs on page load to retrieve questions
        headers: { "X-CSRFToken": csrf_token },
        url:"{% url 'quiz:questions' mode %}",
        type:"POST",
        data:{"start":1},
        success:function(data){
            if(data){
                json_data = data
                unanswered = json_data.question_keys
                askQ()
            }
        }
    })



    function askQ(number=undefined,option=undefined){
        //Displays new question. 
        //Returns false if last option in question has been displayed
        //Returns true if options are remaining in question
        if(number != undefined){
            number = parseInt(number)
            var j = unansweredOptions[number].indexOf(option)
            if (j >= 0) {
                unansweredOptions[number].splice(j, 1);
            }
            if (unansweredOptions[number].length == 0) {
                var i = unanswered.indexOf(number);
                if (i >= 0) {
                    unanswered.splice(i, 1);
                }
                delete(unansweredOptions[number])
                return false
            }
        }
        var question = unanswered[0]
        var options = json_data.questions[question]
        if (question in unansweredOptions == false){
            unansweredOptions[question] = options
            $("form").append(newQuestion(question,unansweredOptions[question][0]))
        }
        else{
            changeOption(question,unansweredOptions[question][0])
        }
        var lastInput = $("input.answer").last()
        lastInput.focus()
        lastInput.on("input",checkInputAnswer)
        lastInput[0].scrollIntoView()
        return true
    }


</script>
{% endblock content %}

quiz/templates/questions.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form action="{% url 'quiz:ajax' %}" method="POST" id="questions-form">
    {% csrf_token %}
</form>
<script>
    var csrf_token = '{{csrf_token}}';
    var modeURL = "{% url 'quiz:questions' mode %}";
</script>
<script src="{% static 'ajax-script.js' %}"></script>
{% endblock content %}